version: '3.3'

services:
  postgresql:
    image: postgres
    container_name: staff
    ports:
      - "5436:5432"
    volumes: 
      - ./dump:/docker-entrypoint-initdb.d
      - ./data/postgres:/var/lib/postgresql/data-personnel 777
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin